
hello=Hello World!

quarkus.log.console.enabled=true
quarkus.log.console.json.enabled=false
quarkus.log.file.enabled=true
quarkus.log.file.path=logs/application.log
quarkus.log.file.json=true
quarkus.log.file.json.pretty-print=true
quarkus.log.level=INFO

quarkus.log.handler.console.demo-log-handler.enabled=true
quarkus.log.handler.console.demo-log-handler.format=%d{yyyy} %-5p [%t] %c{1} - %s%e%n
quarkus.log.handler.console.demo-log-handler.darken=1
quarkus.log.handler.console.demo-log-handler.json.enabled=true
quarkus.log.handler.console.demo-log-handler.json.pretty-print=true
quarkus.log.category."org.acme".handlers=demo-log-handler
quarkus.log.category."org.acme".use-parent-handlers=false

800 726 786