quarkus.http.port=8081

#quarkus.http.access-log.enabled=true
#quarkus.http.record-request-start-time=true
#quarkus.http.access-log.pattern=%t "%r" %s %B %Dms %{ALL_REQUEST_HEADERS}

quarkus.rest.logging.scope=request-response
quarkus.rest.logging.include-body=true
quarkus.rest.logging.body-limit=100
#quarkus.rest.logging.masked-headers=User-Agent,Authorization,Cookie
