quarkus.operator-sdk.crd.validate=false
quarkus.operator-sdk.crd.apply=false
%dev.quarkus.operator-sdk.crd.apply=true
# Serve /q/metrics on the main HTTP port instead of a separate management port
quarkus.management.enabled=false
